[package]
name = "builder"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
proc-macro2 = "1.0.27"
syn = { version = "1.0.73", features = ["full", "extra-traits"] }
